### ISSUE TITLE
Could you share scripts for ViT-B?

### ISSUE THREAD

**Issue by taeoh-kim** [ggjy/FastMIM.pytorch#1]
Thank you for sharing the amazing work!

Could you share scripts for ViT-B as in the results?

I cloned the code and finetune from the official pretrain ckpt of ViT-B using the script below (from the information written in the paper)

```
python -m torch.distributed.launch --nproc_per_node=8 main_finetune.py \
  --model vit_base_patch16 --data_path /path/to/data \
  --batch_size 128 --epochs 100 --blr 1.0e-3 --layer_decay 0.70 --weight_decay 0.05 --drop_path 0.1 --dist_eval \
  --finetune /path/to/pretrained_ckpt --output_dir .
```

I got 83.614 (Top-1) / 86.556 (Top-5) which are slightly lower than the reported.

+ also, the fine-tuned ckpt file of ViT-B seems to be broken.

**Comment by ggjy** [comment]
I think the ```blr 6e-4 ``` should work and get 83.8.

**Comment by taeoh-kim** [comment]
Thank you for the fast reply!

Could you also share the full script of ViT-B for pretrain?

**Comment by ggjy** [comment]
I have uploaded the full script of ViT-B.
